name: 'doctorBot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  doctorbot:
    runs-on: ubuntu-latest
    environment: var
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./doctorbot/requirements.txt
      - name: 'Working'
        run: bash ./doctorbot/main.sh
        env:
          BOOK_DATE: ${{ vars.DATE }}
          SITE: ${{ vars.SITE }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 医生预约
          body: file://email.txt
          to: ${{ secrets.to_email }}
          from: GitHub Actions
          content_type: text/plain

